#************************* makefile for messages **************************

country    =usa-ms

#
#######################	dependencies begin here. #########################
#

all: $(country).idx

$(country).idx: $(country).msg

