;	SCCSID = @(#)comseg.asm 1.1 85/05/14
;	SCCSID = @(#)comseg.asm 1.1 85/05/14
; The following are all of the segments used in the load order

CODERES 	SEGMENT PUBLIC BYTE	;AC000; resident code
CODERES 	ENDS

DATARES 	SEGMENT PUBLIC BYTE	;AC000; resident data
DATARES 	ENDS

BATARENA	SEGMENT PUBLIC PARA	;AC000; space for DOS ALLOCATE header
BATARENA	ENDS

BATSEG		SEGMENT PUBLIC PARA	;AC000; AUTOEXEC batch segment
BATSEG		ENDS

ENVARENA	SEGMENT PUBLIC PARA	;AC000; space for DOS ALLOCATE header
ENVARENA	ENDS

ENVIRONMENT	SEGMENT PUBLIC PARA	;AC000; Default COMMAND environment
ENVIRONMENT	ENDS

INIT		SEGMENT PUBLIC PARA	;AC000; Initialization code
INIT		ENDS

TAIL		SEGMENT PUBLIC PARA	;AC000; End of Init - start of Transient
TAIL		ENDS

TRANCODE	SEGMENT PUBLIC BYTE	;AC000; Transient code
TRANCODE	ENDS

TRANDATA	SEGMENT PUBLIC BYTE	;AC000; Transient data area
TRANDATA	ENDS

TRANSPACE	SEGMENT PUBLIC BYTE	;AC000; Transient modifiable data area
TRANSPACE	ENDS

TRANTAIL	SEGMENT PUBLIC PARA	;AC000; End of Transient
TRANTAIL	ENDS

RESGROUP  GROUP CODERES,DATARES,BATARENA,BATSEG,ENVARENA,ENVIRONMENT,INIT,TAIL
TRANGROUP GROUP TRANCODE,TRANDATA,TRANSPACE,TRANTAIL
