COM=..\COMMON
MSG=..\MESSAGES
country=usa


DRIVER.CTL: DRIVER.SKL  $(MSG)\$(COUNTRY).MSG
            MSGBUILD DRIVER.SKL

DRIVER.OBJ:     DRIVER.ASM  $(COM)\IBMBDS.INC $(COM)\VERSIONA.INC \
                $(COM)\PARSE.ASM $(COM)\PSDATA.INC \
                DRIVER.CTL $(COM)\SYSMSG.INC $(COM)\MSGSERV.ASM
        ASM87 DRIVER

DRIVER.SYS:     DRIVER.OBJ $(COM)\setver.bat DRIVER.ARF
        LINK @DRIVER.ARF
        EXE2BIN DRIVER.EXE DRIVER.SYS
        TAG DRIVER.SYS
        DEL DRIVER.EXE
