copy .\bios\io.sys %1
copy .\dos\msdos.sys %1
copy .\cmd\append\append.exe %1
copy .\cmd\assign\assign.com %1
copy .\cmd\attrib\attrib.exe %1
copy .\cmd\backup\backup.com %1
copy .\cmd\chkdsk\chkdsk.com %1
copy .\cmd\command\command.com %1
copy .\cmd\comp\comp.com %1
copy .\cmd\debug\debug.com %1
copy .\cmd\diskcomp\diskcomp.com %1
copy .\cmd\diskcopy\diskcopy.com %1
copy .\cmd\edlin\edlin.com %1
copy .\cmd\exe2bin\exe2bin.exe %1
copy .\cmd\fastopen\fastopen.exe %1
copy .\cmd\filesys\filesys.exe %1
copy .\cmd\fdisk\fdisk.exe %1
copy .\cmd\find\find.exe %1
copy .\cmd\fc\fc.exe %1
copy .\cmd\format\format.com %1
copy .\cmd\graftabl\graftabl.com %1
copy .\cmd\graphics\graphics.com %1
copy .\cmd\graphics\graphics.pro %1
copy .\cmd\ifsfunc\ifsfunc.exe %1
copy .\cmd\join\join.exe %1
copy .\cmd\label\label.com %1
copy .\cmd\mem\mem.exe %1
copy .\cmd\mode\mode.com %1
copy .\cmd\more\more.com %1
copy .\cmd\nlsfunc\nlsfunc.exe %1
copy .\cmd\print\print.com %1
copy .\cmd\recover\recover.com %1
copy .\cmd\replace\replace.exe %1
copy .\cmd\restore\restore.com %1
copy .\select\select.exe %1
copy .\select\select.com %1
copy .\select\select.dat %1
copy .\select\select.prt %1
copy .\select\select.hlp %1
copy .\cmd\share\share.exe %1
copy .\cmd\sort\sort.exe %1
copy .\cmd\sys\sys.com %1
copy .\cmd\subst\subst.exe %1
copy .\cmd\tree\tree.com %1
copy .\cmd\xcopy\xcopy.exe %1
copy .\cmd\keyb\keyb.com %1
copy .\dev\ansi\ansi.sys %1
copy .\dev\country\country.sys %1
copy .\dev\display\display.sys %1
copy .\dev\display\ega\ega.cpi %1
copy .\dev\display\lcd\lcd.cpi %1
copy .\dev\keyboard\keyboard.sys %1
copy .\dev\printer\printer.sys %1
copy .\dev\printer\4201\4201.cpi %1
copy .\dev\printer\4208\4208.cpi %1
copy .\dev\printer\5202\5202.cpi %1
copy .\dev\smartdrv\smartdrv.sys %1
copy .\dev\ramdrive\ramdrive.sys %1
copy .\dev\driver\driver.sys %1
copy .\dev\xma2ems\xma2ems.sys %1
copy .\dev\xmaem\xmaem.sys %1
copy .\memm\memm\emm386.sys %1
