.xlist
;
;
;*****************************************************************************
;*                                                                           *
;* Change list to EXE2BIN modules                                            *
;*                                                                           *
;* Lines are tagged ANxxx for new, ACxxx for changed                         *
;* --------------------------------------------------------------------------*
;*  000 - DOS 4.00 Spec additions and DCR's thru unit/function test          *
;*         Date: 12/31/87  Developer: Dennis M	                             *
;* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
;*  001 - DOS 4.00 PTM P3964 Pass invalid parameter to message retriever for *
;*         replacement in error message.                                     *
;*         Date: 03/24/88  Developer: Dennis M	                             *
;* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
;*****************************************************************************
;* Note: This is file E2BCHNG.INC for updating purposes                      *
;*****************************************************************************
.list

