                                                ;                               ;     ;

NO      equ     0
YES     equ     not NO


DOS_Found equ   0

INIT    equ     0


Net_Check equ   1200h
Assign_Check equ 8000h

Found_Yes equ   1
Found_No equ    0

Asciiz_End equ  0
;DBCS    equ     81h
DBCS_Blank equ  40h
DBCS_Vector_Size equ 2
End_Of_Vector equ 0


Blank   equ     " "

Label_Length equ 11
CR      equ     13

DBCS_VECTOR equ NO

;-------------------------------------------------------------------------------





DRNUM   EQU     5CH



; Exit status defines
ExitOK  equ     0


;-------------------------------------------------------------------------------
; These are the data structures which we will need


