.xlist
;
;
;*****************************************************************************
;*                                                                           *
;* Change list to FILESYS modules                                            *
;*                                                                           *
;* Lines are tagged ANxxx for new, ACxxx for changed                         *
;* --------------------------------------------------------------------------*
;*  000 - DOS 4.00 Spec additions and DCR's thru unit/function test          *
;*         Date: 12/31/87  Developer: GA, DS		             *
;* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
;*  001 - DOS 4.00 PTM P4249 FILESYS adds extra ":" on forth entry of display.*
;*         Date: 04/22/88  Developer: DM                               *
;* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
;*  002 - DOS 4.00 PTM P4248 FILESYS does not show PAUSED in status field,   *
;*        also added was ERROR to the status field.                          *
;*         Date: 04/22/88  Developer: DM                               *
;* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
;*****************************************************************************
;* Note: This is file FSCHNG.INC for updating purposes                       *
;*****************************************************************************
.list

