;
; CAS Routine Numbers
;
; Revised:  10-05-87
;
BX_RN          EQU  3009H             ;DRAWBOX    PCBOXDR   FABOXDR
CC_RN          EQU  2100H             ;CALCLOR    PCCOLOR   FACOLOR
CR_RN          EQU  2101H             ;CROWCOL    PCROWCL   FAROWCL
CE_RN          EQU  5000H             ;CRITERR    PCCRITE   FACRITE
CM_RN          EQU  3001H             ;COMPRSS    PCCOMPS   FACOMPS
CRD_RN         EQU  210BH             ;           PCCLRRD
CWR_RN         EQU  210CH             ;           PCCLRWR
DTS_RN         EQU  4001H             ;DATES      PCDATES   FADATES
FF_RN          EQU  1300H             ;FINDFLS    PCFINDF   FAFINDF
GV_RN          EQU  2102H             ;GETVIDO    PCGVIDO   FAGVIDO
GE_RN          EQU  4000H             ;GETEQUP    PCGEQUP   FAGEQUP
HWR_RN         EQU  2108H             ;           PCHLPRD
HRD_RN         EQU  2109H             ;           PCHLPWR
INS_RN         EQU  300BH             ;INSTRG     PCINSTR   FAINSTR
I2S_RN         EQU  3000H             ;CIS        PCIN2ST   FAIN2ST
MB_RN          EQU  2400H             ;MAKEBEEP   PCMBEEP   FAMBEEP
MO_RN          EQU  3002H             ;MOVECON    PCMOVEC   FAMOVEC
MI_RN          EQU  3003H             ;MOVEINT    PCMOVEI   FAMOVEI
MS_RN          EQU  1200H             ;TRACKER    PCTRACK
MX_RN          EQU  3004H             ;MOVEMIX    PCMOVEM   FAMOVEM
PM_RN          EQU  2103H             ;PANMAN     PCPANEL   FAPANEL
PWR_RN         EQU  2106H             ;           PCPANWR
PRD_RN         EQU  210AH             ;           PCPANRD
QM_RN          EQU  2111H             ;           PCDISPQ
SF_RN          EQU  2107H             ;SETFLAG    PCSTATF   FASTATF
SV_RN          EQU  2104H             ;SETVIDO    PCSVIDO   FASVIDO
SK_RN          EQU  1102H             ;SIMKEY     PCSIMKY   FASIMKY
SRD_RN         EQU  210DH             ;           PCSCRRD
SWR_RN         EQU  210EH             ;           PCSCRWR
SM_RN          EQU  300DH             ;           PCPANSM
SCB_RN         EQU  2105H             ;SLCTOPT    PCSLCTP
SO_RN          EQU  2105H             ;SLCTOPT              FASLCTP
SS_RN          EQU  3005H             ;STRGSRT    PCSORTS   FASORTS
SSC_RN         EQU  300AH             ;STRSTRC    PCSTRST   FASTRST
TMS_RN         EQU  4002H             ;TIMES      PCTIMES   FATIMES
WN_RN          EQU  3007H             ;WINDOW     PCWINDO   FAWINDO
S2I_RN         EQU  300EH             ;           PCST2IN
WWP_RN         EQU  300FH             ;           PCWWRAP             PCGRPRD
GWR_RN         EQU  3010H             ;           PCGRPWR             PCGRPWR
GRD_RN         EQU  3011H             ;           PCGRPRD             PCGRPRD
IWR_RN         EQU  3012H             ;           PCINPWR             PCINPWR
IRD_RN         EQU  3013H             ;           PCINPRD             PCINPRD
M1_RN          EQU  3014H             ;                               PCMSDRV
M1_RN          EQU  3014H             ;                               PCIBMDRV
INC_RN         EQU  3015H             ;           PCINCHA             PCINCHA
DBC_RN         EQU  3016H             ;           PCINDBC             PCINDBC
C0H_RN         EQU  3017H             ;           PCGEQUP
MRD_RN         EQU  3018H             ;
NWR_RN         EQU  3019H             ;
IN_RN          EQU  301AH             ;           PCINPUT             PCINPUT
MG_RN          EQU  301BH             ;           PCINPUT             PCINPUT
MWR_RN         EQU  301CH             ;           PCMEUWR             PCMEUWR
;
