;	SCCSID = @(#)dosseg.asm	1.1 85/04/10
;	SCCSID = @(#)dosseg.asm	1.1 85/04/10
;
; segment ordering for MSDOS
;

START		SEGMENT BYTE PUBLIC 'START'
START		ENDS

CONSTANTS	SEGMENT WORD PUBLIC 'CONST'
CONSTANTS	ENDS

DATA		SEGMENT WORD PUBLIC 'DATA'
DATA		ENDS

TABLE		SEGMENT BYTE PUBLIC 'TABLE'
TABLE		ENDS

CODE		SEGMENT BYTE PUBLIC 'CODE'
CODE		ENDS

LAST		SEGMENT PARA PUBLIC 'LAST'
LAST		ENDS

DOSGROUP    GROUP   START,CONSTANTS,DATA,TABLE,CODE,LAST
